// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDNS(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetActiveDNS():Promise<string>;

export function GetDNSList():Promise<Record<string, Array<string>>>;

export function PingDNS():Promise<string>;

export function SetDNS(arg1:string):Promise<string>;
