// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDNS(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDNS'](arg1, arg2, arg3);
}

export function GetActiveDNS() {
  return window['go']['main']['App']['GetActiveDNS']();
}

export function GetDNSList() {
  return window['go']['main']['App']['GetDNSList']();
}

export function PingDNS() {
  return window['go']['main']['App']['PingDNS']();
}

export function SetDNS(arg1) {
  return window['go']['main']['App']['SetDNS'](arg1);
}
